export const environment = {
  production: true,
  envName: 'production',
  maApiUrl: 'https://vbrick.marketingassociates.com/',
  apiImagePath: 'https://vbrick.marketingassociates.com/uploads/', 
  vbrickUrl: 'https://forddealersrev.dealerconnection.com',
  videoUrl: 'https://forddealersrev.dealerconnection.com/embed?id=',
  fordtubeUrl: 'https://fordtube.dealerconnection.com',
  vbrickApiKey: '458832E5C72BB77EF7FAB74C7CE55',
  lincolnUrl: 'https://lincolnvideogallery.dealerconnection.com',
  vbrickReportsUrl: 'https://forddealersrev.dealerconnection.com/#/admin/ae7dc5b1-69ee-440e-9d4c-02af660b1fe3/reports',
  googleAnalytics: { domain: 'auto', trackingId: 'UA-11235517-1' },
  franchise: 0,
  adfsDomain: 'https://corp.sts.ford.com/adfs',
  adfsClientId: 'urn:allvm.dealerconnection.com:clientid:web_alldealerconn:prod',
  adfsRedirectUri: 'https://fordtube.dealerconnection.com/signin-oidc',
  adfsResource: 'urn:allvm.dealerconnection.com:resource:web_alldealerconn:prod',
};
