//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExactTargetService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageCustomParameter", Namespace="http://tempuri.org/")]
    public partial class MessageCustomParameter : object
    {
        
        private string NameField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UniqueResponse", Namespace="http://tempuri.org/")]
    public partial class UniqueResponse : object
    {
        
        private string statusCodeField;
        
        private string statusMessageField;
        
        private string resultCodeField;
        
        private string uniqueIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string statusMessage
        {
            get
            {
                return this.statusMessageField;
            }
            set
            {
                this.statusMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string resultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string uniqueID
        {
            get
            {
                return this.uniqueIDField;
            }
            set
            {
                this.uniqueIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExactTargetService.ExactTargetServiceSoap")]
    public interface ExactTargetServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<ExactTargetService.SendEmailResponse> SendEmailAsync(ExactTargetService.SendEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendFulfillmentEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<ExactTargetService.SendFulfillmentEmailResponse> SendFulfillmentEmailAsync(ExactTargetService.SendFulfillmentEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOLAEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<ExactTargetService.SendOLAEmailResponse> SendOLAEmailAsync(ExactTargetService.SendOLAEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendExactTargetFullCustomParams", ReplyAction="*")]
        System.Threading.Tasks.Task<ExactTargetService.SendExactTargetFullCustomParamsResponse> SendExactTargetFullCustomParamsAsync(ExactTargetService.SendExactTargetFullCustomParamsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendExactTargetWithCustomParams", ReplyAction="*")]
        System.Threading.Tasks.Task<ExactTargetService.SendExactTargetWithCustomParamsResponse> SendExactTargetWithCustomParamsAsync(ExactTargetService.SendExactTargetWithCustomParamsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendExactTargetEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<ExactTargetService.SendExactTargetEmailResponse> SendExactTargetEmailAsync(ExactTargetService.SendExactTargetEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendExactTargetEmail2", ReplyAction="*")]
        System.Threading.Tasks.Task<ExactTargetService.SendExactTargetEmail2Response> SendExactTargetEmail2Async(ExactTargetService.SendExactTargetEmail2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExactTargetResult", ReplyAction="*")]
        System.Threading.Tasks.Task<ExactTargetService.GetExactTargetResultResponse> GetExactTargetResultAsync(ExactTargetService.GetExactTargetResultRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmail", Namespace="http://tempuri.org/", Order=0)]
        public ExactTargetService.SendEmailRequestBody Body;
        
        public SendEmailRequest()
        {
        }
        
        public SendEmailRequest(ExactTargetService.SendEmailRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmailRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string emailContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string toEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fromEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fromName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string customerKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string statusMessage;
        
        public SendEmailRequestBody()
        {
        }
        
        public SendEmailRequestBody(string emailContent, string subject, string toEmail, string fromEmail, string fromName, string customerKey, string statusMessage)
        {
            this.emailContent = emailContent;
            this.subject = subject;
            this.toEmail = toEmail;
            this.fromEmail = fromEmail;
            this.fromName = fromName;
            this.customerKey = customerKey;
            this.statusMessage = statusMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExactTargetService.SendEmailResponseBody Body;
        
        public SendEmailResponse()
        {
        }
        
        public SendEmailResponse(ExactTargetService.SendEmailResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmailResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendEmailResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string statusMessage;
        
        public SendEmailResponseBody()
        {
        }
        
        public SendEmailResponseBody(string SendEmailResult, string statusMessage)
        {
            this.SendEmailResult = SendEmailResult;
            this.statusMessage = statusMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFulfillmentEmailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendFulfillmentEmail", Namespace="http://tempuri.org/", Order=0)]
        public ExactTargetService.SendFulfillmentEmailRequestBody Body;
        
        public SendFulfillmentEmailRequest()
        {
        }
        
        public SendFulfillmentEmailRequest(ExactTargetService.SendFulfillmentEmailRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendFulfillmentEmailRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string eCert;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string vehBrand;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string toEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string fromEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fromName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string customerKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string statusMessage;
        
        public SendFulfillmentEmailRequestBody()
        {
        }
        
        public SendFulfillmentEmailRequestBody(string eCert, string firstName, string lastName, string vehBrand, string subject, string toEmail, string fromEmail, string fromName, string customerKey, string statusMessage)
        {
            this.eCert = eCert;
            this.firstName = firstName;
            this.lastName = lastName;
            this.vehBrand = vehBrand;
            this.subject = subject;
            this.toEmail = toEmail;
            this.fromEmail = fromEmail;
            this.fromName = fromName;
            this.customerKey = customerKey;
            this.statusMessage = statusMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFulfillmentEmailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendFulfillmentEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExactTargetService.SendFulfillmentEmailResponseBody Body;
        
        public SendFulfillmentEmailResponse()
        {
        }
        
        public SendFulfillmentEmailResponse(ExactTargetService.SendFulfillmentEmailResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendFulfillmentEmailResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendFulfillmentEmailResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string statusMessage;
        
        public SendFulfillmentEmailResponseBody()
        {
        }
        
        public SendFulfillmentEmailResponseBody(string SendFulfillmentEmailResult, string statusMessage)
        {
            this.SendFulfillmentEmailResult = SendFulfillmentEmailResult;
            this.statusMessage = statusMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendOLAEmailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendOLAEmail", Namespace="http://tempuri.org/", Order=0)]
        public ExactTargetService.SendOLAEmailRequestBody Body;
        
        public SendOLAEmailRequest()
        {
        }
        
        public SendOLAEmailRequest(ExactTargetService.SendOLAEmailRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendOLAEmailRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string eCert;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string custName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string toEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string fromEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string fromName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string customerKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string expDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string statusMessage;
        
        public SendOLAEmailRequestBody()
        {
        }
        
        public SendOLAEmailRequestBody(string eCert, string custName, string address, string subject, string toEmail, string fromEmail, string fromName, string customerKey, string expDate, string statusMessage)
        {
            this.eCert = eCert;
            this.custName = custName;
            this.address = address;
            this.subject = subject;
            this.toEmail = toEmail;
            this.fromEmail = fromEmail;
            this.fromName = fromName;
            this.customerKey = customerKey;
            this.expDate = expDate;
            this.statusMessage = statusMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendOLAEmailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendOLAEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExactTargetService.SendOLAEmailResponseBody Body;
        
        public SendOLAEmailResponse()
        {
        }
        
        public SendOLAEmailResponse(ExactTargetService.SendOLAEmailResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendOLAEmailResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendOLAEmailResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string statusMessage;
        
        public SendOLAEmailResponseBody()
        {
        }
        
        public SendOLAEmailResponseBody(string SendOLAEmailResult, string statusMessage)
        {
            this.SendOLAEmailResult = SendOLAEmailResult;
            this.statusMessage = statusMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendExactTargetFullCustomParamsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendExactTargetFullCustomParams", Namespace="http://tempuri.org/", Order=0)]
        public ExactTargetService.SendExactTargetFullCustomParamsRequestBody Body;
        
        public SendExactTargetFullCustomParamsRequest()
        {
        }
        
        public SendExactTargetFullCustomParamsRequest(ExactTargetService.SendExactTargetFullCustomParamsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendExactTargetFullCustomParamsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string toEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fromEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fromName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string customerKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string statusMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string bccEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ccEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public ExactTargetService.MessageCustomParameter[] messageParameters;
        
        public SendExactTargetFullCustomParamsRequestBody()
        {
        }
        
        public SendExactTargetFullCustomParamsRequestBody(string subject, string toEmail, string fromEmail, string fromName, string customerKey, string statusMessage, string bccEmail, string ccEmail, ExactTargetService.MessageCustomParameter[] messageParameters)
        {
            this.subject = subject;
            this.toEmail = toEmail;
            this.fromEmail = fromEmail;
            this.fromName = fromName;
            this.customerKey = customerKey;
            this.statusMessage = statusMessage;
            this.bccEmail = bccEmail;
            this.ccEmail = ccEmail;
            this.messageParameters = messageParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendExactTargetFullCustomParamsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendExactTargetFullCustomParamsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExactTargetService.SendExactTargetFullCustomParamsResponseBody Body;
        
        public SendExactTargetFullCustomParamsResponse()
        {
        }
        
        public SendExactTargetFullCustomParamsResponse(ExactTargetService.SendExactTargetFullCustomParamsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendExactTargetFullCustomParamsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendExactTargetFullCustomParamsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string statusMessage;
        
        public SendExactTargetFullCustomParamsResponseBody()
        {
        }
        
        public SendExactTargetFullCustomParamsResponseBody(string SendExactTargetFullCustomParamsResult, string statusMessage)
        {
            this.SendExactTargetFullCustomParamsResult = SendExactTargetFullCustomParamsResult;
            this.statusMessage = statusMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendExactTargetWithCustomParamsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendExactTargetWithCustomParams", Namespace="http://tempuri.org/", Order=0)]
        public ExactTargetService.SendExactTargetWithCustomParamsRequestBody Body;
        
        public SendExactTargetWithCustomParamsRequest()
        {
        }
        
        public SendExactTargetWithCustomParamsRequest(ExactTargetService.SendExactTargetWithCustomParamsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendExactTargetWithCustomParamsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string toEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fromEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fromName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string customerKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string statusMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string eCert;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string custName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string address2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string expDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string VIN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string bccEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string ccEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public ExactTargetService.MessageCustomParameter[] messageParameters;
        
        public SendExactTargetWithCustomParamsRequestBody()
        {
        }
        
        public SendExactTargetWithCustomParamsRequestBody(
                    string subject, 
                    string toEmail, 
                    string fromEmail, 
                    string fromName, 
                    string customerKey, 
                    string statusMessage, 
                    string eCert, 
                    string custName, 
                    string address, 
                    string address2, 
                    string expDate, 
                    string VIN, 
                    string Phone, 
                    string bccEmail, 
                    string ccEmail, 
                    ExactTargetService.MessageCustomParameter[] messageParameters)
        {
            this.subject = subject;
            this.toEmail = toEmail;
            this.fromEmail = fromEmail;
            this.fromName = fromName;
            this.customerKey = customerKey;
            this.statusMessage = statusMessage;
            this.eCert = eCert;
            this.custName = custName;
            this.address = address;
            this.address2 = address2;
            this.expDate = expDate;
            this.VIN = VIN;
            this.Phone = Phone;
            this.bccEmail = bccEmail;
            this.ccEmail = ccEmail;
            this.messageParameters = messageParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendExactTargetWithCustomParamsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendExactTargetWithCustomParamsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExactTargetService.SendExactTargetWithCustomParamsResponseBody Body;
        
        public SendExactTargetWithCustomParamsResponse()
        {
        }
        
        public SendExactTargetWithCustomParamsResponse(ExactTargetService.SendExactTargetWithCustomParamsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendExactTargetWithCustomParamsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendExactTargetWithCustomParamsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string statusMessage;
        
        public SendExactTargetWithCustomParamsResponseBody()
        {
        }
        
        public SendExactTargetWithCustomParamsResponseBody(string SendExactTargetWithCustomParamsResult, string statusMessage)
        {
            this.SendExactTargetWithCustomParamsResult = SendExactTargetWithCustomParamsResult;
            this.statusMessage = statusMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendExactTargetEmailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendExactTargetEmail", Namespace="http://tempuri.org/", Order=0)]
        public ExactTargetService.SendExactTargetEmailRequestBody Body;
        
        public SendExactTargetEmailRequest()
        {
        }
        
        public SendExactTargetEmailRequest(ExactTargetService.SendExactTargetEmailRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendExactTargetEmailRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string toEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fromEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fromName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string customerKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string statusMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string eCert;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string custName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string address2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string expDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string VIN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string param1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string param2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string param3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string param4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string param5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string param6;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string param7;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string param8;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string param9;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string param10;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string bccEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string ccEmail;
        
        public SendExactTargetEmailRequestBody()
        {
        }
        
        public SendExactTargetEmailRequestBody(
                    string subject, 
                    string toEmail, 
                    string fromEmail, 
                    string fromName, 
                    string customerKey, 
                    string statusMessage, 
                    string eCert, 
                    string custName, 
                    string address, 
                    string address2, 
                    string expDate, 
                    string VIN, 
                    string Phone, 
                    string param1, 
                    string param2, 
                    string param3, 
                    string param4, 
                    string param5, 
                    string param6, 
                    string param7, 
                    string param8, 
                    string param9, 
                    string param10, 
                    string bccEmail, 
                    string ccEmail)
        {
            this.subject = subject;
            this.toEmail = toEmail;
            this.fromEmail = fromEmail;
            this.fromName = fromName;
            this.customerKey = customerKey;
            this.statusMessage = statusMessage;
            this.eCert = eCert;
            this.custName = custName;
            this.address = address;
            this.address2 = address2;
            this.expDate = expDate;
            this.VIN = VIN;
            this.Phone = Phone;
            this.param1 = param1;
            this.param2 = param2;
            this.param3 = param3;
            this.param4 = param4;
            this.param5 = param5;
            this.param6 = param6;
            this.param7 = param7;
            this.param8 = param8;
            this.param9 = param9;
            this.param10 = param10;
            this.bccEmail = bccEmail;
            this.ccEmail = ccEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendExactTargetEmailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendExactTargetEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExactTargetService.SendExactTargetEmailResponseBody Body;
        
        public SendExactTargetEmailResponse()
        {
        }
        
        public SendExactTargetEmailResponse(ExactTargetService.SendExactTargetEmailResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendExactTargetEmailResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendExactTargetEmailResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string statusMessage;
        
        public SendExactTargetEmailResponseBody()
        {
        }
        
        public SendExactTargetEmailResponseBody(string SendExactTargetEmailResult, string statusMessage)
        {
            this.SendExactTargetEmailResult = SendExactTargetEmailResult;
            this.statusMessage = statusMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendExactTargetEmail2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendExactTargetEmail2", Namespace="http://tempuri.org/", Order=0)]
        public ExactTargetService.SendExactTargetEmail2RequestBody Body;
        
        public SendExactTargetEmail2Request()
        {
        }
        
        public SendExactTargetEmail2Request(ExactTargetService.SendExactTargetEmail2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendExactTargetEmail2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string toEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fromEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fromName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string customerKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string UniqueID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string eCert;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string custName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string address2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string expDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string VIN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string param1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string param2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string param3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string param4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string param5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string param6;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string param7;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string bccEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string ccEmail;
        
        public SendExactTargetEmail2RequestBody()
        {
        }
        
        public SendExactTargetEmail2RequestBody(
                    string subject, 
                    string toEmail, 
                    string fromEmail, 
                    string fromName, 
                    string customerKey, 
                    string UniqueID, 
                    string eCert, 
                    string custName, 
                    string address, 
                    string address2, 
                    string expDate, 
                    string VIN, 
                    string Phone, 
                    string param1, 
                    string param2, 
                    string param3, 
                    string param4, 
                    string param5, 
                    string param6, 
                    string param7, 
                    string bccEmail, 
                    string ccEmail)
        {
            this.subject = subject;
            this.toEmail = toEmail;
            this.fromEmail = fromEmail;
            this.fromName = fromName;
            this.customerKey = customerKey;
            this.UniqueID = UniqueID;
            this.eCert = eCert;
            this.custName = custName;
            this.address = address;
            this.address2 = address2;
            this.expDate = expDate;
            this.VIN = VIN;
            this.Phone = Phone;
            this.param1 = param1;
            this.param2 = param2;
            this.param3 = param3;
            this.param4 = param4;
            this.param5 = param5;
            this.param6 = param6;
            this.param7 = param7;
            this.bccEmail = bccEmail;
            this.ccEmail = ccEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendExactTargetEmail2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendExactTargetEmail2Response", Namespace="http://tempuri.org/", Order=0)]
        public ExactTargetService.SendExactTargetEmail2ResponseBody Body;
        
        public SendExactTargetEmail2Response()
        {
        }
        
        public SendExactTargetEmail2Response(ExactTargetService.SendExactTargetEmail2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendExactTargetEmail2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExactTargetService.UniqueResponse SendExactTargetEmail2Result;
        
        public SendExactTargetEmail2ResponseBody()
        {
        }
        
        public SendExactTargetEmail2ResponseBody(ExactTargetService.UniqueResponse SendExactTargetEmail2Result)
        {
            this.SendExactTargetEmail2Result = SendExactTargetEmail2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExactTargetResultRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExactTargetResult", Namespace="http://tempuri.org/", Order=0)]
        public ExactTargetService.GetExactTargetResultRequestBody Body;
        
        public GetExactTargetResultRequest()
        {
        }
        
        public GetExactTargetResultRequest(ExactTargetService.GetExactTargetResultRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExactTargetResultRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uniqueID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string customerKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string emailAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string response;
        
        public GetExactTargetResultRequestBody()
        {
        }
        
        public GetExactTargetResultRequestBody(string uniqueID, string customerKey, string emailAddress, string response)
        {
            this.uniqueID = uniqueID;
            this.customerKey = customerKey;
            this.emailAddress = emailAddress;
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExactTargetResultResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExactTargetResultResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExactTargetService.GetExactTargetResultResponseBody Body;
        
        public GetExactTargetResultResponse()
        {
        }
        
        public GetExactTargetResultResponse(ExactTargetService.GetExactTargetResultResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExactTargetResultResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExactTargetResultResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string response;
        
        public GetExactTargetResultResponseBody()
        {
        }
        
        public GetExactTargetResultResponseBody(string GetExactTargetResultResult, string response)
        {
            this.GetExactTargetResultResult = GetExactTargetResultResult;
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ExactTargetServiceSoapChannel : ExactTargetService.ExactTargetServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ExactTargetServiceSoapClient : System.ServiceModel.ClientBase<ExactTargetService.ExactTargetServiceSoap>, ExactTargetService.ExactTargetServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ExactTargetServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ExactTargetServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ExactTargetServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExactTargetServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ExactTargetServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExactTargetServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ExactTargetServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExactTargetServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExactTargetService.SendEmailResponse> ExactTargetService.ExactTargetServiceSoap.SendEmailAsync(ExactTargetService.SendEmailRequest request)
        {
            return base.Channel.SendEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExactTargetService.SendEmailResponse> SendEmailAsync(string emailContent, string subject, string toEmail, string fromEmail, string fromName, string customerKey, string statusMessage)
        {
            ExactTargetService.SendEmailRequest inValue = new ExactTargetService.SendEmailRequest();
            inValue.Body = new ExactTargetService.SendEmailRequestBody();
            inValue.Body.emailContent = emailContent;
            inValue.Body.subject = subject;
            inValue.Body.toEmail = toEmail;
            inValue.Body.fromEmail = fromEmail;
            inValue.Body.fromName = fromName;
            inValue.Body.customerKey = customerKey;
            inValue.Body.statusMessage = statusMessage;
            return ((ExactTargetService.ExactTargetServiceSoap)(this)).SendEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExactTargetService.SendFulfillmentEmailResponse> ExactTargetService.ExactTargetServiceSoap.SendFulfillmentEmailAsync(ExactTargetService.SendFulfillmentEmailRequest request)
        {
            return base.Channel.SendFulfillmentEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExactTargetService.SendFulfillmentEmailResponse> SendFulfillmentEmailAsync(string eCert, string firstName, string lastName, string vehBrand, string subject, string toEmail, string fromEmail, string fromName, string customerKey, string statusMessage)
        {
            ExactTargetService.SendFulfillmentEmailRequest inValue = new ExactTargetService.SendFulfillmentEmailRequest();
            inValue.Body = new ExactTargetService.SendFulfillmentEmailRequestBody();
            inValue.Body.eCert = eCert;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.vehBrand = vehBrand;
            inValue.Body.subject = subject;
            inValue.Body.toEmail = toEmail;
            inValue.Body.fromEmail = fromEmail;
            inValue.Body.fromName = fromName;
            inValue.Body.customerKey = customerKey;
            inValue.Body.statusMessage = statusMessage;
            return ((ExactTargetService.ExactTargetServiceSoap)(this)).SendFulfillmentEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExactTargetService.SendOLAEmailResponse> ExactTargetService.ExactTargetServiceSoap.SendOLAEmailAsync(ExactTargetService.SendOLAEmailRequest request)
        {
            return base.Channel.SendOLAEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExactTargetService.SendOLAEmailResponse> SendOLAEmailAsync(string eCert, string custName, string address, string subject, string toEmail, string fromEmail, string fromName, string customerKey, string expDate, string statusMessage)
        {
            ExactTargetService.SendOLAEmailRequest inValue = new ExactTargetService.SendOLAEmailRequest();
            inValue.Body = new ExactTargetService.SendOLAEmailRequestBody();
            inValue.Body.eCert = eCert;
            inValue.Body.custName = custName;
            inValue.Body.address = address;
            inValue.Body.subject = subject;
            inValue.Body.toEmail = toEmail;
            inValue.Body.fromEmail = fromEmail;
            inValue.Body.fromName = fromName;
            inValue.Body.customerKey = customerKey;
            inValue.Body.expDate = expDate;
            inValue.Body.statusMessage = statusMessage;
            return ((ExactTargetService.ExactTargetServiceSoap)(this)).SendOLAEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExactTargetService.SendExactTargetFullCustomParamsResponse> ExactTargetService.ExactTargetServiceSoap.SendExactTargetFullCustomParamsAsync(ExactTargetService.SendExactTargetFullCustomParamsRequest request)
        {
            return base.Channel.SendExactTargetFullCustomParamsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExactTargetService.SendExactTargetFullCustomParamsResponse> SendExactTargetFullCustomParamsAsync(string subject, string toEmail, string fromEmail, string fromName, string customerKey, string statusMessage, string bccEmail, string ccEmail, ExactTargetService.MessageCustomParameter[] messageParameters)
        {
            ExactTargetService.SendExactTargetFullCustomParamsRequest inValue = new ExactTargetService.SendExactTargetFullCustomParamsRequest();
            inValue.Body = new ExactTargetService.SendExactTargetFullCustomParamsRequestBody();
            inValue.Body.subject = subject;
            inValue.Body.toEmail = toEmail;
            inValue.Body.fromEmail = fromEmail;
            inValue.Body.fromName = fromName;
            inValue.Body.customerKey = customerKey;
            inValue.Body.statusMessage = statusMessage;
            inValue.Body.bccEmail = bccEmail;
            inValue.Body.ccEmail = ccEmail;
            inValue.Body.messageParameters = messageParameters;
            return ((ExactTargetService.ExactTargetServiceSoap)(this)).SendExactTargetFullCustomParamsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExactTargetService.SendExactTargetWithCustomParamsResponse> ExactTargetService.ExactTargetServiceSoap.SendExactTargetWithCustomParamsAsync(ExactTargetService.SendExactTargetWithCustomParamsRequest request)
        {
            return base.Channel.SendExactTargetWithCustomParamsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExactTargetService.SendExactTargetWithCustomParamsResponse> SendExactTargetWithCustomParamsAsync(
                    string subject, 
                    string toEmail, 
                    string fromEmail, 
                    string fromName, 
                    string customerKey, 
                    string statusMessage, 
                    string eCert, 
                    string custName, 
                    string address, 
                    string address2, 
                    string expDate, 
                    string VIN, 
                    string Phone, 
                    string bccEmail, 
                    string ccEmail, 
                    ExactTargetService.MessageCustomParameter[] messageParameters)
        {
            ExactTargetService.SendExactTargetWithCustomParamsRequest inValue = new ExactTargetService.SendExactTargetWithCustomParamsRequest();
            inValue.Body = new ExactTargetService.SendExactTargetWithCustomParamsRequestBody();
            inValue.Body.subject = subject;
            inValue.Body.toEmail = toEmail;
            inValue.Body.fromEmail = fromEmail;
            inValue.Body.fromName = fromName;
            inValue.Body.customerKey = customerKey;
            inValue.Body.statusMessage = statusMessage;
            inValue.Body.eCert = eCert;
            inValue.Body.custName = custName;
            inValue.Body.address = address;
            inValue.Body.address2 = address2;
            inValue.Body.expDate = expDate;
            inValue.Body.VIN = VIN;
            inValue.Body.Phone = Phone;
            inValue.Body.bccEmail = bccEmail;
            inValue.Body.ccEmail = ccEmail;
            inValue.Body.messageParameters = messageParameters;
            return ((ExactTargetService.ExactTargetServiceSoap)(this)).SendExactTargetWithCustomParamsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExactTargetService.SendExactTargetEmailResponse> ExactTargetService.ExactTargetServiceSoap.SendExactTargetEmailAsync(ExactTargetService.SendExactTargetEmailRequest request)
        {
            return base.Channel.SendExactTargetEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExactTargetService.SendExactTargetEmailResponse> SendExactTargetEmailAsync(
                    string subject, 
                    string toEmail, 
                    string fromEmail, 
                    string fromName, 
                    string customerKey, 
                    string statusMessage, 
                    string eCert, 
                    string custName, 
                    string address, 
                    string address2, 
                    string expDate, 
                    string VIN, 
                    string Phone, 
                    string param1, 
                    string param2, 
                    string param3, 
                    string param4, 
                    string param5, 
                    string param6, 
                    string param7, 
                    string param8, 
                    string param9, 
                    string param10, 
                    string bccEmail, 
                    string ccEmail)
        {
            ExactTargetService.SendExactTargetEmailRequest inValue = new ExactTargetService.SendExactTargetEmailRequest();
            inValue.Body = new ExactTargetService.SendExactTargetEmailRequestBody();
            inValue.Body.subject = subject;
            inValue.Body.toEmail = toEmail;
            inValue.Body.fromEmail = fromEmail;
            inValue.Body.fromName = fromName;
            inValue.Body.customerKey = customerKey;
            inValue.Body.statusMessage = statusMessage;
            inValue.Body.eCert = eCert;
            inValue.Body.custName = custName;
            inValue.Body.address = address;
            inValue.Body.address2 = address2;
            inValue.Body.expDate = expDate;
            inValue.Body.VIN = VIN;
            inValue.Body.Phone = Phone;
            inValue.Body.param1 = param1;
            inValue.Body.param2 = param2;
            inValue.Body.param3 = param3;
            inValue.Body.param4 = param4;
            inValue.Body.param5 = param5;
            inValue.Body.param6 = param6;
            inValue.Body.param7 = param7;
            inValue.Body.param8 = param8;
            inValue.Body.param9 = param9;
            inValue.Body.param10 = param10;
            inValue.Body.bccEmail = bccEmail;
            inValue.Body.ccEmail = ccEmail;
            return ((ExactTargetService.ExactTargetServiceSoap)(this)).SendExactTargetEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExactTargetService.SendExactTargetEmail2Response> ExactTargetService.ExactTargetServiceSoap.SendExactTargetEmail2Async(ExactTargetService.SendExactTargetEmail2Request request)
        {
            return base.Channel.SendExactTargetEmail2Async(request);
        }
        
        public System.Threading.Tasks.Task<ExactTargetService.SendExactTargetEmail2Response> SendExactTargetEmail2Async(
                    string subject, 
                    string toEmail, 
                    string fromEmail, 
                    string fromName, 
                    string customerKey, 
                    string UniqueID, 
                    string eCert, 
                    string custName, 
                    string address, 
                    string address2, 
                    string expDate, 
                    string VIN, 
                    string Phone, 
                    string param1, 
                    string param2, 
                    string param3, 
                    string param4, 
                    string param5, 
                    string param6, 
                    string param7, 
                    string bccEmail, 
                    string ccEmail)
        {
            ExactTargetService.SendExactTargetEmail2Request inValue = new ExactTargetService.SendExactTargetEmail2Request();
            inValue.Body = new ExactTargetService.SendExactTargetEmail2RequestBody();
            inValue.Body.subject = subject;
            inValue.Body.toEmail = toEmail;
            inValue.Body.fromEmail = fromEmail;
            inValue.Body.fromName = fromName;
            inValue.Body.customerKey = customerKey;
            inValue.Body.UniqueID = UniqueID;
            inValue.Body.eCert = eCert;
            inValue.Body.custName = custName;
            inValue.Body.address = address;
            inValue.Body.address2 = address2;
            inValue.Body.expDate = expDate;
            inValue.Body.VIN = VIN;
            inValue.Body.Phone = Phone;
            inValue.Body.param1 = param1;
            inValue.Body.param2 = param2;
            inValue.Body.param3 = param3;
            inValue.Body.param4 = param4;
            inValue.Body.param5 = param5;
            inValue.Body.param6 = param6;
            inValue.Body.param7 = param7;
            inValue.Body.bccEmail = bccEmail;
            inValue.Body.ccEmail = ccEmail;
            return ((ExactTargetService.ExactTargetServiceSoap)(this)).SendExactTargetEmail2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExactTargetService.GetExactTargetResultResponse> ExactTargetService.ExactTargetServiceSoap.GetExactTargetResultAsync(ExactTargetService.GetExactTargetResultRequest request)
        {
            return base.Channel.GetExactTargetResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExactTargetService.GetExactTargetResultResponse> GetExactTargetResultAsync(string uniqueID, string customerKey, string emailAddress, string response)
        {
            ExactTargetService.GetExactTargetResultRequest inValue = new ExactTargetService.GetExactTargetResultRequest();
            inValue.Body = new ExactTargetService.GetExactTargetResultRequestBody();
            inValue.Body.uniqueID = uniqueID;
            inValue.Body.customerKey = customerKey;
            inValue.Body.emailAddress = emailAddress;
            inValue.Body.response = response;
            return ((ExactTargetService.ExactTargetServiceSoap)(this)).GetExactTargetResultAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ExactTargetServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ExactTargetServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ExactTargetServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://services.onemagnify.com/sfmc-api/ExactTargetService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ExactTargetServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://services.onemagnify.com/sfmc-api/ExactTargetService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ExactTargetServiceSoap,
            
            ExactTargetServiceSoap12,
        }
    }
}
